name: Build, Test, and Deploy to AWS ECR

on:
  push:
    branches:
      - main  # Runs only when pushing to 'main' branch
  workflow_dispatch:  # Allows manual execution

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build --no-cache -t test-python-image .

      - name: Test Python Version Inside Container
        run: |
          docker run --rm --entrypoint python test-python-image --version

  deploy:
    needs: test-build  # Ensures testing passes before deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (IAM Keys)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com

      - name: Make deploy.sh Executable
        run: chmod +x deploy.sh

      - name: Run Deploy Script
        run: ./deploy.sh
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          REGION: "ap-southeast-1"
